// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqlcxberbeibitgxojcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxbGN4YmVyYmVpYml0Z3hvamN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjkxMDQsImV4cCI6MjA2ODg0NTEwNH0.IvLXg5SmNi7AgowHG883pK0HBCoaSh8BVBWao9HoMMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});